import { useCallback, useEffect, useState } from 'react'
import { apiUrl, handleUnauthorized } from '../../../api/client'
import { Archive, ArrowDownToLine, Bell, BriefcaseBusiness, Check, ChevronLeft, CircleAlert, ClipboardList, FileClock, LayoutDashboard, LogOut, Receipt, Settings2 } from 'lucide-react'
import './finance.css'
import logo from '../../../assets/logo.png'

type User = { name: string; email: string; role: 'finance' }
type Tab = 'overview' | 'work' | 'invoices' | 'projects' | 'exceptions' | 'audit' | 'notifications'

async function api(path: string, token: string, method = 'GET', body?: object) {
  const response = await fetch(apiUrl(`/finance${path}`), { method, headers: { Authorization: `Bearer ${token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) })
  if (handleUnauthorized(response.status)) throw new Error('Your session has expired. Please sign in again.')
  const text = await response.text(); let data: any = {}
  try { data = text ? JSON.parse(text) : {} } catch { data = { message: 'The server returned an unreadable response.' } }
  if (!response.ok) throw new Error(data.message || 'Unable to complete Finance action.')
  return data
}

function money(value: unknown, currency: string) {
  if (value == null || !Number.isFinite(Number(value))) return '—'
  try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(Number(value)) } catch { return `${currency} ${Number(value).toFixed(2)}` }
}

async function downloadCsv(path: string, token: string) {
  const response = await fetch(apiUrl(`/finance${path}`), { headers: { Authorization: `Bearer ${token}` } })
  if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.message || 'Unable to export this report.') }
  const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = response.headers.get('Content-Disposition')?.match(/filename="?([^";]+)"?/)?.[1] || 'pulseai-finance.csv'; link.click(); URL.revokeObjectURL(url)
}

export function FinanceDashboard({ user, onSignOut }: { user: User; onSignOut: () => void }) {
  const token = localStorage.getItem('pulseai_token') || ''
  const [tab, setTab] = useState<Tab>('overview'); const [data, setData] = useState<any>(null); const [projects, setProjects] = useState<any[]>([]); const [clients, setClients] = useState<any[]>([]); const [selectedInvoice, setSelectedInvoice] = useState<number | null>(null); const [requestedProjectId, setRequestedProjectId] = useState<number | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => {
    try {
      const [dashboard, projectData, clientData] = await Promise.all([api('/dashboard', token), api('/projects', token), api('/clients', token)])
      setData(dashboard); setProjects(projectData.projects); setClients(clientData.clients); setError('')
    } catch (err) { setError(err instanceof Error ? err.message : 'Finance data could not be loaded.') }
  }, [token])
  useEffect(() => { load() }, [load])
  const finishAction = async (text: string) => { setMessage(text); await load() }
  const exportFile = async (kind: string) => { setBusy(true); try { await downloadCsv(`/exports/${kind}`, token); setMessage('CSV export downloaded.') } catch (err) { setError(err instanceof Error ? err.message : 'Unable to download export.') } finally { setBusy(false) } }
  const unread = data?.notifications?.filter((item: any) => !item.readAt).length || 0
  const nav: Array<[Tab, string, typeof LayoutDashboard]> = [['overview', 'Overview', LayoutDashboard], ['work', 'Approved work', ClipboardList], ['invoices', 'Invoices', Receipt], ['projects', 'Projects & rates', BriefcaseBusiness], ['exceptions', 'Exceptions', CircleAlert], ['audit', 'Finance audit', FileClock], ['notifications', 'Notifications', Bell]]
  const title = selectedInvoice ? 'Invoice detail' : ({ overview: 'Finance overview', work: 'Approved work', invoices: 'Invoices', projects: 'Projects & rates', exceptions: 'Financial exceptions', audit: 'Finance audit', notifications: 'Notifications' }[tab])
  return <main className="finance-app"><aside className="finance-sidebar"><div className="finance-logo"><img src={logo} alt="" /> pulse<span>AI</span></div><p>FINANCE WORKSPACE</p><nav aria-label="Finance workspace">{nav.map(([id, label, Icon]) => <button key={id} type="button" className={!selectedInvoice && tab === id ? 'active' : ''} onClick={() => { setSelectedInvoice(null); setRequestedProjectId(null); setTab(id) }}><Icon size={17} />{label}{id === 'notifications' && unread > 0 ? <small>{unread}</small> : null}</button>)}</nav><div className="finance-user"><span>{user.name[0]}</span><div><strong>{user.name}</strong><small>Finance</small></div><button type="button" aria-label="Sign out" onClick={onSignOut}><LogOut size={16} /></button></div></aside>
    <section className="finance-content"><header className="finance-header"><div>{selectedInvoice ? <button type="button" className="finance-back" onClick={() => setSelectedInvoice(null)}><ChevronLeft size={16} />Back to invoices</button> : null}<h1>{title}</h1><p>{data?.period ? `${data.period} · Manager-approved work only` : 'Manager-approved work and client billing'}</p></div><div className="finance-header-actions"><button type="button" className="finance-button quiet" disabled={busy} onClick={() => exportFile(tab === 'invoices' || selectedInvoice ? 'invoice-lines' : 'unbilled-work')}><ArrowDownToLine size={15} />Export CSV</button><span className="finance-period">{data?.period || 'No active period'}</span></div></header>
      {error ? <div className="finance-message error" role="alert">{error}<button type="button" onClick={load}>Retry</button></div> : null}{message ? <div className="finance-message" role="status">{message}<button type="button" onClick={() => setMessage('')} aria-label="Dismiss message">×</button></div> : null}
      {!data && !error ? <div className="finance-loading" aria-live="polite"><span /><p>Loading Finance records…</p></div> : null}
      {data && !selectedInvoice && tab === 'overview' ? <Overview data={data} onNavigate={setTab} onProject={(id: number) => { setRequestedProjectId(id); setTab('projects') }} onInvoice={(id: number) => setSelectedInvoice(id)} /> : null}
      {data && !selectedInvoice && tab === 'work' ? <ApprovedWork token={token} projects={projects} clients={clients} onDone={finishAction} onInvoice={(id: number) => { setSelectedInvoice(id); setTab('invoices') }} /> : null}
      {data && !selectedInvoice && tab === 'invoices' ? <Invoices token={token} clients={clients} onOpen={(id: number) => setSelectedInvoice(id)} /> : null}
      {data && selectedInvoice ? <InvoiceDetail token={token} invoiceId={selectedInvoice} onDone={finishAction} /> : null}
      {data && !selectedInvoice && tab === 'projects' ? <Projects token={token} projects={projects} clients={clients} initialProjectId={requestedProjectId} onExport={() => exportFile('project-summary')} onDone={finishAction} /> : null}
      {data && !selectedInvoice && tab === 'exceptions' ? <Exceptions token={token} onProject={(id: number) => { setRequestedProjectId(id); setTab('projects') }} onInvoice={(id: number) => setSelectedInvoice(id)} /> : null}
      {data && !selectedInvoice && tab === 'audit' ? <Audit token={token} /> : null}
      {data && !selectedInvoice && tab === 'notifications' ? <Notifications token={token} rows={data.notifications || []} onRefresh={load} onWork={() => setTab('work')} /> : null}
    </section></main>
}

function Overview({ data, onNavigate, onProject, onInvoice }: any) {
  const metrics = data.metrics || {}; const amounts = metrics.unbilledAmounts || []
  return <>
    <dl className="finance-metrics"><div><dt>Approved hours awaiting processing</dt><dd>{Number(metrics.approvedHoursAwaitingProcessing || 0).toFixed(1)}<small>h</small></dd></div><div><dt>Billable hours</dt><dd>{Number(metrics.billableHours || 0).toFixed(1)}<small>h</small></dd></div><div><dt>Non-billable hours</dt><dd>{Number(metrics.nonBillableHours || 0).toFixed(1)}<small>h</small></dd></div><div><dt>Unbilled value</dt><dd className="finance-amounts">{amounts.length ? amounts.map((row: any) => <span key={row.currency}>{money(row.amount, row.currency)}</span>) : '—'}</dd></div></dl>
    <section className="finance-section"><div className="finance-section-heading"><div><h2>Attention required</h2><p>Resolve configuration gaps before creating or finalizing invoices.</p></div><button type="button" className="finance-link" onClick={() => onNavigate('exceptions')}>All exceptions <span>→</span></button></div>
      {data.exceptions?.length ? <div className="finance-attention">{data.exceptions.slice(0, 8).map((item: any, index: number) => <article key={`${item.entryId || item.invoiceId}-${index}`}><span className={`finance-severity ${item.severity || 'warning'}`}>{item.severity || 'Review'}</span><div><strong>{item.employeeName || item.invoiceNumber || item.projectName}</strong><p>{item.exception || item.message}</p><small>{item.projectCode || item.periodLabel || item.entryDate || ''}</small></div><button type="button" className="finance-button quiet" onClick={() => item.invoiceId ? onInvoice(Number(item.invoiceId)) : item.projectId ? onProject(Number(item.projectId)) : onNavigate('work')}>{item.invoiceId ? 'Review invoice' : item.projectId ? 'Configure project' : 'View work'}</button></article>)}</div> : <p className="finance-empty">No financial exceptions in the active reporting period.</p>}
    </section>
    <section className="finance-section"><div className="finance-section-heading"><div><h2>Invoice pipeline</h2><p>Current invoice statuses from Finance records.</p></div><button type="button" className="finance-link" onClick={() => onNavigate('invoices')}>Open invoices <span>→</span></button></div><div className="finance-pipeline"><div><span>Drafts</span><strong>{metrics.draftInvoices.count}</strong><small>{formatTotals(metrics.draftInvoices.totals)}</small></div><div><span>Ready</span><strong>{metrics.readyInvoices.count}</strong><small>{formatTotals(metrics.readyInvoices.totals)}</small></div><div><span>Finalized</span><strong>{metrics.finalizedInvoices.count}</strong><small>{formatTotals(metrics.finalizedInvoices.totals)}</small></div></div></section>
    <div className="finance-quick-actions"><button type="button" onClick={() => onNavigate('work')}><ClipboardList size={16} />Review approved work</button><button type="button" onClick={() => onNavigate('projects')}><Settings2 size={16} />Configure clients and rates</button><button type="button" onClick={() => onNavigate('invoices')}><Receipt size={16} />Review invoice drafts</button></div>
  </>
}

function formatTotals(rows: any[] = []) { return rows.length ? rows.map((row) => money(row.amount, row.currency)).join(' · ') : '—' }

function ApprovedWork({ token, projects, clients, onDone, onInvoice }: any) {
  const [periods, setPeriods] = useState<any[]>([]); const [employees, setEmployees] = useState<any[]>([]); const [rows, setRows] = useState<any[]>([]); const [selected, setSelected] = useState<number[]>([]); const [filters, setFilters] = useState({ period: '', projectId: '', clientId: '', employeeId: '', billingStatus: 'all', billable: 'all' }); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([api('/periods', token), api('/options', token)]).then(([periodData, options]) => { setPeriods(periodData.periods); setEmployees(options.employees) }).catch((err) => setError(err instanceof Error ? err.message : 'Filter options unavailable.')) }, [token])
  const search = useCallback(async () => { setLoading(true); setError(''); try { const params = new URLSearchParams(); for (const [key, value] of Object.entries(filters)) if (value) params.set(key, value); const result = await api(`/entries?${params}`, token); setRows(result.entries); setSelected([]) } catch (err) { setError(err instanceof Error ? err.message : 'Approved work could not be loaded.') } finally { setLoading(false) } }, [filters, token])
  useEffect(() => { search() }, [search])
  const createDraft = async () => { try { const result = await api('/invoices', token, 'POST', { entryIds: selected }); await onDone(result.message); onInvoice(Number(result.invoiceId)) } catch (err) { setError(err instanceof Error ? err.message : 'Invoice draft could not be created.') } }
  const toggle = (id: number) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  return <section className="finance-table-section"><div className="finance-filters">
    <label>Reporting period<select value={filters.period} onChange={(event) => setFilters({ ...filters, period: event.target.value })}><option value="">All periods</option>{periods.map((item: any) => <option key={item.periodLabel} value={item.periodLabel}>{item.periodLabel}</option>)}</select></label>
    <label>Project<select value={filters.projectId} onChange={(event) => setFilters({ ...filters, projectId: event.target.value })}><option value="">All projects</option>{projects.map((item: any) => <option key={item.id} value={item.id}>{item.code}</option>)}</select></label>
    <label>Client<select value={filters.clientId} onChange={(event) => setFilters({ ...filters, clientId: event.target.value })}><option value="">All clients</option>{clients.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label>Employee<select value={filters.employeeId} onChange={(event) => setFilters({ ...filters, employeeId: event.target.value })}><option value="">All employees</option>{employees.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label>Billing status<select value={filters.billingStatus} onChange={(event) => setFilters({ ...filters, billingStatus: event.target.value })}><option value="all">All</option><option value="unbilled">Unbilled</option><option value="draft">Draft invoice</option><option value="ready">Ready invoice</option><option value="finalized">Finalized</option></select></label>
    <label>Classification<select value={filters.billable} onChange={(event) => setFilters({ ...filters, billable: event.target.value })}><option value="all">All</option><option value="billable">Billable</option><option value="nonbillable">Non-billable</option><option value="unclassified">Unclassified</option></select></label>
    <button type="button" className="finance-button quiet" onClick={search}>Apply filters</button>
  </div>
    {error ? <div className="finance-inline-error" role="alert">{error}</div> : null}
    <div className="finance-table-tools"><span>{loading ? 'Loading approved entries…' : `${rows.length} approved entr${rows.length === 1 ? 'y' : 'ies'}`}</span><div><button type="button" className="finance-button quiet" onClick={() => downloadCsv('approved-work', token)}>Export approved work</button><button type="button" className="finance-button quiet" onClick={() => downloadCsv('unbilled-work', token)}>Export unbilled only</button><button type="button" className="finance-button primary" disabled={!selected.length || loading} onClick={createDraft}><Receipt size={15} />Create draft from {selected.length} selected</button></div></div>
    <Table headings={['', 'Work date', 'Employee', 'Project / activity', 'Client', 'Class', 'Hours', 'Rate', 'Amount', 'Billing status']} rows={rows.map((row) => <tr key={row.entryId}><td><input aria-label={`Select approved entry ${row.entryId}`} type="checkbox" disabled={!row.eligibleForInvoice} checked={selected.includes(Number(row.entryId))} onChange={() => toggle(Number(row.entryId))} /></td><td>{row.entryDate}<small>{row.periodLabel}</small></td><td><strong>{row.employeeName}</strong><small>{row.employeeCode}</small></td><td><strong>{row.projectCode || 'Internal'}</strong><small>{row.activityName}</small></td><td>{row.clientName || '—'}</td><td><span className={`finance-state ${row.financialClass}`}>{row.financialClass}</span></td><td className="finance-number">{Number(row.hours).toFixed(2)}</td><td>{row.rateAmount == null ? '—' : money(row.rateAmount, row.rateCurrency || row.clientCurrency)}</td><td className="finance-number">{row.amount == null ? '—' : money(row.amount, row.clientCurrency)}</td><td><span className={`finance-state ${row.billingStatus}`}>{row.billingStatus}</span>{row.exception ? <small className="finance-row-warning">{row.exception}</small> : null}</td></tr>)} empty={loading ? 'Loading approved work…' : 'No Manager-approved work matches these filters.'} />
  </section>
}

function Invoices({ token, clients, onOpen }: any) {
  const [rows, setRows] = useState<any[]>([]); const [status, setStatus] = useState(''); const [period, setPeriod] = useState(''); const [clientId, setClientId] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams(); if (status) params.set('status', status); if (period) params.set('period', period); if (clientId) params.set('clientId', clientId); const result = await api(`/invoices?${params}`, token); setRows(result.invoices); setError('') } catch (err) { setError(err instanceof Error ? err.message : 'Invoices could not be loaded.') } finally { setLoading(false) } }, [token, status, period, clientId])
  useEffect(() => { load() }, [load])
  return <section className="finance-table-section"><div className="finance-filters"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="ready">Ready</option><option value="finalized">Finalized</option><option value="cancelled">Cancelled</option></select></label><label>Billing period<input value={period} onChange={(event) => setPeriod(event.target.value)} placeholder="e.g. September 2026" /></label><label>Client<select value={clientId} onChange={(event) => setClientId(event.target.value)}><option value="">All clients</option>{clients.map((client: any) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><button type="button" className="finance-button quiet" onClick={() => downloadCsv('invoices', token)}>Export invoice summary</button></div>{error ? <div className="finance-inline-error" role="alert">{error}</div> : null}<Table headings={['Invoice', 'Client', 'Period', 'Projects', 'Lines', 'Amount', 'Status', 'Created', '']} rows={rows.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.invoiceNumber}</strong></td><td>{invoice.clientName}<small>{invoice.clientCode}</small></td><td>{invoice.periodLabel}</td><td>{invoice.projects || '—'}</td><td>{invoice.lineCount}</td><td className="finance-number">{money(invoice.subtotal, invoice.currency)}</td><td><span className={`finance-state ${invoice.status}`}>{invoice.status}</span></td><td>{new Date(invoice.createdAt).toLocaleDateString()}</td><td><button type="button" className="finance-button quiet" onClick={() => onOpen(Number(invoice.id))}>Open</button></td></tr>)} empty={loading ? 'Loading invoices…' : 'No invoices match these filters. Build a draft from eligible approved work.'} /></section>
}

function InvoiceDetail({ token, invoiceId, onDone }: any) {
  const [detail, setDetail] = useState<any>(null); const [error, setError] = useState(''); const [confirm, setConfirm] = useState<'finalize' | 'cancel' | null>(null); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { try { setDetail(await api(`/invoices/${invoiceId}`, token)); setError('') } catch (err) { setError(err instanceof Error ? err.message : 'Invoice details could not be loaded.') } }, [invoiceId, token])
  useEffect(() => { load() }, [load])
  const action = async (path: string, method = 'POST') => { setBusy(true); try { const result = await api(path, token, method); setConfirm(null); await load(); await onDone(result.message) } catch (err) { setError(err instanceof Error ? err.message : 'Invoice action failed.') } finally { setBusy(false) } }
  if (!detail) return <div className="finance-loading">{error || 'Loading invoice…'}</div>
  const invoice = detail.invoice
  return <section className="finance-invoice-detail"><header className="finance-invoice-heading"><div><span className={`finance-state ${invoice.status}`}>{invoice.status}</span><h2>{invoice.invoiceNumber}</h2><p>{invoice.clientName} · {invoice.periodLabel} · {invoice.currency}</p></div><strong>{money(invoice.subtotal, invoice.currency)}</strong></header>
    {error ? <div className="finance-inline-error" role="alert">{error}</div> : null}
    {invoice.status === 'cancelled' ? <p className="finance-finalized-note">Cancelled draft · {invoice.cancelledLineCount || 0} source entries were released. The original line snapshot is retained in Finance audit.</p> : null}
    <Table headings={['Source entry', 'Work date', 'Employee', 'Project / activity', 'Description', 'Hours', 'Rate', 'Line amount']} rows={detail.lines.map((line: any) => <tr key={line.id}><td>#{line.entryId}</td><td>{line.entryDate}</td><td><strong>{line.employeeName}</strong><small>{line.employeeCode}</small></td><td><strong>{line.projectCode}</strong><small>{line.activityName}</small></td><td>{line.workDescription || '—'}</td><td className="finance-number">{Number(line.hours).toFixed(2)}</td><td>{money(line.rate, line.currency)}</td><td className="finance-number">{money(line.amount, line.currency)}</td></tr>)} empty={invoice.status === 'cancelled' ? 'Cancelled invoice lines were released and are preserved in Finance audit.' : 'This invoice has no source entries.'} />
    <div className="finance-invoice-actions">{confirm ? <div className="finance-confirm" role="alert"><strong>{confirm === 'finalize' ? 'Finalize and lock this invoice?' : 'Cancel this draft?'}</strong><span>{confirm === 'finalize' ? 'The invoice and its rate, currency, hours, and amounts become read-only.' : 'The draft lines will be released and can be billed again.'}</span><button type="button" className="finance-button quiet" onClick={() => setConfirm(null)}>Keep invoice</button><button type="button" className="finance-button primary" disabled={busy} onClick={() => action(confirm === 'finalize' ? `/invoices/${invoiceId}/finalize` : `/invoices/${invoiceId}`, confirm === 'cancel' ? 'DELETE' : 'POST')}>{busy ? 'Saving…' : confirm === 'finalize' ? 'Confirm finalize' : 'Confirm cancel'}</button></div> : null}
      {!confirm && invoice.status === 'draft' ? <><button type="button" className="finance-button quiet danger" onClick={() => setConfirm('cancel')}>Cancel draft</button><button type="button" className="finance-button primary" onClick={() => action(`/invoices/${invoiceId}/ready`)}><Check size={15} />Mark ready</button></> : null}
      {!confirm && invoice.status === 'ready' ? <button type="button" className="finance-button primary" onClick={() => setConfirm('finalize')}><Archive size={15} />Finalize invoice</button> : null}
      {invoice.status === 'finalized' ? <span className="finance-finalized-note">Finalized {invoice.finalizedAt ? `on ${new Date(invoice.finalizedAt).toLocaleDateString()}` : ''}{invoice.finalizedBy ? ` by ${invoice.finalizedBy}` : ''}. Historical snapshot is locked.</span> : null}
    </div></section>
}

function Projects({ token, projects, clients, initialProjectId, onExport, onDone }: any) {
  const [selectedId, setSelectedId] = useState<number | null>(initialProjectId || null); const [clientForm, setClientForm] = useState({ code: '', name: '', currency: '', billingEmail: '' }); const [error, setError] = useState('')
  const createClient = async () => { try { const result = await api('/clients', token, 'POST', clientForm); setClientForm({ code: '', name: '', currency: '', billingEmail: '' }); await onDone(result.message) } catch (err) { setError(err instanceof Error ? err.message : 'Client could not be created.') } }
  const toggleClient = async (client: any) => { try { const result = await api(`/clients/${client.id}`, token, 'PATCH', { active: !client.active }); await onDone(result.message) } catch (err) { setError(err instanceof Error ? err.message : 'Client status could not be updated.') } }
  return <section className="finance-projects"><div className="finance-client-setup"><div className="finance-section-heading"><div><h2>Client billing records</h2><p>Client currency is the billing currency for linked projects.</p></div></div><div className="finance-client-form"><label>Client code<input value={clientForm.code} onChange={(event) => setClientForm({ ...clientForm, code: event.target.value.toUpperCase() })} maxLength={40} placeholder="ACME" /></label><label>Client name<input value={clientForm.name} onChange={(event) => setClientForm({ ...clientForm, name: event.target.value })} maxLength={160} placeholder="Acme Corporation" /></label><label>Currency<input value={clientForm.currency} onChange={(event) => setClientForm({ ...clientForm, currency: event.target.value.toUpperCase() })} maxLength={3} placeholder="USD" /></label><label>Billing email <span>optional</span><input type="email" value={clientForm.billingEmail} onChange={(event) => setClientForm({ ...clientForm, billingEmail: event.target.value })} placeholder="ap@example.com" /></label><button type="button" className="finance-button primary" disabled={!clientForm.code || !clientForm.name || clientForm.currency.length !== 3} onClick={createClient}>Add client</button></div>{error ? <p className="finance-inline-error" role="alert">{error}</p> : null}<Table headings={['Client', 'Billing contact', 'Currency', 'State', '']} rows={clients.map((client: any) => <tr key={client.id}><td><strong>{client.code}</strong><small>{client.name}</small></td><td>{client.billingEmail || 'Not set'}</td><td>{client.currency}</td><td><span className={`finance-state ${client.active ? 'active' : 'inactive'}`}>{client.active ? 'active' : 'inactive'}</span></td><td><button type="button" className="finance-link" onClick={() => toggleClient(client)}>{client.active ? 'Deactivate' : 'Reactivate'}</button></td></tr>)} empty="No client billing profiles yet." /></div>
    <div className="finance-section-heading finance-project-heading"><div><h2>Project financial position</h2><p>Operational projects remain shared; Finance maintains only their billing configuration.</p></div><div><span>{projects.length} projects </span><button type="button" className="finance-button quiet" onClick={onExport}>Export project summary</button></div></div>
    <Table headings={['Project', 'Client', 'Approved h', 'Billable h', 'Non-billable h', 'Unbilled h / amount', 'Billed h / amount', '']} rows={projects.map((project: any) => <tr key={project.id}><td><strong>{project.code}</strong><small>{project.name}</small></td><td>{project.clientName || <span className="finance-row-warning">Client required</span>}</td><td className="finance-number">{project.approvedHours.toFixed(2)}</td><td className="finance-number">{project.billableHours.toFixed(2)}</td><td className="finance-number">{project.nonBillableHours.toFixed(2)}</td><td className="finance-number">{project.unbilledHours.toFixed(2)} h<small>{project.currency ? money(project.unbilledAmount, project.currency) : 'Rate/client required'}</small></td><td className="finance-number">{project.billedHours.toFixed(2)} h<small>{project.currency ? money(project.billedAmount, project.currency) : '—'}</small></td><td><button type="button" className="finance-button quiet" onClick={() => setSelectedId(Number(project.id))}>{selectedId === Number(project.id) ? 'Open' : 'Configure'}</button></td></tr>)} empty="No shared projects are available." />
    {selectedId ? <ProjectDetail token={token} projectId={selectedId} clients={clients} onDone={onDone} onClose={() => setSelectedId(null)} /> : null}
  </section>
}

function ProjectDetail({ token, projectId, clients, onDone, onClose }: any) {
  const [detail, setDetail] = useState<any>(null); const [rate, setRate] = useState({ amount: '', effectiveFrom: new Date().toISOString().slice(0, 10), effectiveTo: '' }); const [error, setError] = useState('')
  const load = useCallback(async () => { try { setDetail(await api(`/projects/${projectId}`, token)); setError('') } catch (err) { setError(err instanceof Error ? err.message : 'Project billing details unavailable.') } }, [projectId, token])
  useEffect(() => { load() }, [load])
  const saveRate = async () => { try { const result = await api(`/projects/${projectId}/rates`, token, 'POST', { ...rate, currency: detail.project.currency }); setRate({ ...rate, amount: '', effectiveTo: '' }); await load(); await onDone(result.message) } catch (err) { setError(err instanceof Error ? err.message : 'Billing rate could not be saved.') } }
  const changeClassification = async (activityId: number, value: string) => { try { const result = await api(`/projects/${projectId}/activities/${activityId}`, token, 'PATCH', { billable: value === 'unclassified' ? null : value === 'billable' }); await load(); await onDone(result.message) } catch (err) { setError(err instanceof Error ? err.message : 'Classification could not be updated.') } }
  const changeClient = async (clientId: string) => { try { const result = await api(`/projects/${projectId}/client`, token, 'PATCH', { clientId: clientId || null }); await load(); await onDone(result.message) } catch (err) { setError(err instanceof Error ? err.message : 'Project client could not be updated.') } }
  if (!detail) return <section className="finance-project-detail">{error || 'Loading project configuration…'}</section>
  return <section className="finance-project-detail"><div className="finance-section-heading"><div><h2>{detail.project.code} · Billing configuration</h2><p>{detail.project.name}</p></div><button type="button" className="finance-button quiet" onClick={onClose}>Close</button></div>{error ? <div className="finance-inline-error" role="alert">{error}</div> : null}
    <label className="finance-project-client">Client<select value={detail.project.clientId || ''} onChange={(event) => changeClient(event.target.value)}><option value="">No client configured</option>{clients.filter((client: any) => client.active).map((client: any) => <option key={client.id} value={client.id}>{client.code} · {client.name} ({client.currency})</option>)}</select></label>
    <div className="finance-subheading"><h3>Activity classification</h3><span>Internal activities are treated as non-billable.</span></div><Table headings={['Activity', 'Type', 'Billing classification']} rows={detail.activities.map((item: any) => <tr key={item.activityId}><td>{item.activityName}</td><td>{item.category}</td><td>{item.category === 'internal' ? <span className="finance-state nonbillable">Non-billable</span> : <select aria-label={`Billing classification for ${item.activityName}`} value={item.billable == null ? 'unclassified' : item.billable ? 'billable' : 'nonbillable'} onChange={(event) => changeClassification(Number(item.activityId), event.target.value)}><option value="unclassified">Unclassified</option><option value="billable">Billable</option><option value="nonbillable">Non-billable</option></select>}</td></tr>)} empty="No activities are configured for this project." />
    <div className="finance-subheading"><div><h3>Effective billing rates</h3><span>Amounts are snapshots on invoice lines; finalized invoices never recalculate.</span></div></div>{detail.project.currency ? <div className="finance-rate-form"><label>Rate ({detail.project.currency})<input type="number" min="0.0001" step="0.0001" value={rate.amount} onChange={(event) => setRate({ ...rate, amount: event.target.value })} /></label><label>Effective from<input type="date" value={rate.effectiveFrom} onChange={(event) => setRate({ ...rate, effectiveFrom: event.target.value })} /></label><label>Effective to <span>optional</span><input type="date" value={rate.effectiveTo} onChange={(event) => setRate({ ...rate, effectiveTo: event.target.value })} /></label><button type="button" className="finance-button primary" disabled={!rate.amount || !detail.project.clientId} onClick={saveRate}>Add rate version</button></div> : <p className="finance-inline-note">Link an active client before setting a billing rate.</p>}
    <Table headings={['Rate', 'Currency', 'Effective from', 'Effective to', 'State', '']} rows={detail.rates.map((item: any) => <tr key={item.id}><td>{money(item.amount, item.currency)}</td><td>{item.currency}</td><td>{item.effectiveFrom}</td><td>{item.effectiveTo || 'Open'}</td><td><span className={`finance-state ${item.active ? 'active' : 'inactive'}`}>{item.active ? 'active' : 'ended'}</span></td><td>{item.active ? <button type="button" className="finance-link danger" onClick={async () => { try { await api(`/rates/${item.id}/active`, token, 'PATCH', { active: false }); await load(); await onDone('Rate ended; historical rate dates remain available.') } catch (err) { setError(err instanceof Error ? err.message : 'Rate could not be ended.') } }}>End rate</button> : null}</td></tr>)} empty="No billing rate covers this project yet." />
  </section>
}

function Exceptions({ token, onProject, onInvoice }: any) {
  const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { api('/exceptions', token).then((data) => setRows(data.exceptions)).catch((err) => setError(err instanceof Error ? err.message : 'Exceptions unavailable.')).finally(() => setLoading(false)) }, [token])
  return <section className="finance-table-section"><div className="finance-section-heading"><div><h2>Billing validation</h2><p>Blocking items prevent invoice creation or finalization. Warnings indicate work reserved in a draft or ready invoice.</p></div><span>{rows.length} items</span></div>{error ? <p className="finance-inline-error" role="alert">{error}</p> : null}<Table headings={['Severity', 'Work / invoice', 'Project', 'Issue', 'Period', 'Action']} rows={rows.map((item, index) => <tr key={`${item.entryId || item.invoiceId}-${index}`}><td><span className={`finance-severity ${item.severity}`}>{item.severity}</span></td><td>{item.employeeName || item.invoiceNumber || `Entry #${item.entryId}`}</td><td>{item.projectCode || '—'}</td><td>{item.exception || item.message}</td><td>{item.periodLabel || '—'}</td><td>{item.invoiceId ? <button type="button" className="finance-button quiet" onClick={() => onInvoice(Number(item.invoiceId))}>Open invoice</button> : item.projectId ? <button type="button" className="finance-button quiet" onClick={() => onProject(Number(item.projectId))}>Configure</button> : null}</td></tr>)} empty={loading ? 'Checking approved work…' : 'No financial exceptions need attention.'} /></section>
}

function Audit({ token }: { token: string }) {
  const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { api('/audit', token).then((data) => setRows(data.events)).catch((err) => setError(err instanceof Error ? err.message : 'Finance audit unavailable.')).finally(() => setLoading(false)) }, [token])
  return <section className="finance-audit"><div className="finance-section-heading"><div><h2>Financial change history</h2><p>Rate, classification, client, and invoice decisions are recorded with their before and after values.</p></div></div>{error ? <div className="finance-inline-error">{error}</div> : null}{loading ? <p className="finance-inline-note">Loading Finance audit…</p> : rows.length ? rows.map((event) => <article key={event.id}><div><strong>{event.action.replaceAll('_', ' ')}</strong><span>{event.entityType} #{event.entityId}</span></div><p>{event.beforeState ? `${event.beforeState} → ` : ''}{event.afterState || 'Recorded'}</p><small>{event.actorName} · {new Date(event.createdAt).toLocaleString()}</small></article>) : <p className="finance-empty">No Finance changes have been recorded yet.</p>}</section>
}

function Notifications({ token, rows, onRefresh, onWork }: any) {
  const markRead = async (id: number) => { await api(`/notifications/${id}/read`, token, 'POST'); onRefresh() }
  return <section className="finance-notifications">{rows.length ? rows.map((item: any) => <article key={item.id} className={item.readAt ? '' : 'unread'}><div><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString()}</small></div><div>{item.timesheetId ? <button type="button" className="finance-link" onClick={onWork}>Review approved work <small>(timesheet #{item.timesheetId})</small></button> : null}{!item.readAt ? <button type="button" className="finance-link" onClick={() => markRead(item.id)}>Mark read</button> : null}</div></article>) : <p className="finance-empty">Finance notifications appear when Manager-approved work is ready for processing.</p>}</section>
}

function Table({ headings, rows, empty }: { headings: string[]; rows: any[]; empty: string }) {
  return <div className="finance-table-wrap" tabIndex={0} role="region" aria-label={`${headings[0]} table`}><table><thead><tr>{headings.map((heading, index) => <th key={`${heading}-${index}`}>{heading}</th>)}</tr></thead><tbody>{rows.length ? rows : <tr><td className="finance-table-empty" colSpan={headings.length}>{empty}</td></tr>}</tbody></table></div>
}
