import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { CalendarDays, LogOut, Users, UserCog } from 'lucide-react'
import './employee.css'
import './hr.css'

type User = { name: string; email: string; role: 'hr' }
type Tab = 'workforce' | 'leave' | 'calendar'
const token = () => localStorage.getItem('pulseai_token') || ''
async function api(path: string, method = 'GET', body?: object) {
  const response = await fetch(`/api/hr${path}`, { method, headers: { Authorization: `Bearer ${token()}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) })
  const text = await response.text(); const data = text ? JSON.parse(text) : {}
  if (!response.ok) throw new Error(data.message || 'Unable to update the workforce record.')
  return data
}

export function HRDashboard({ user, onSignOut }: { user: User; onSignOut: () => void }) {
  const [tab, setTab] = useState<Tab>('workforce'); const [data, setData] = useState<any>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const [employee, setEmployee] = useState({ employeeCode: '', name: '', email: '', departmentId: '', managerUserId: '' })
  const [leave, setLeave] = useState({ employeeId: '', startsOn: '', endsOn: '', leaveType: 'Annual leave', sourceReference: '' })
  const [holiday, setHoliday] = useState({ holidayDate: '', name: '', region: 'default' })
  const load = useCallback(async () => { try { const result = await api('/overview'); setData(result); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load HR workspace.') } }, [])
  useEffect(() => { void load() }, [load])
  const save = async (work: () => Promise<unknown>, success: string) => { setSaving(true); setError(''); setMessage(''); try { await work(); await load(); setMessage(success) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save changes.') } finally { setSaving(false) } }
  const addEmployee = (event: FormEvent) => { event.preventDefault(); void save(async () => { await api('/employees', 'POST', { ...employee, departmentId: Number(employee.departmentId), managerUserId: Number(employee.managerUserId) }); setEmployee({ employeeCode: '', name: '', email: '', departmentId: '', managerUserId: '' }) }, 'Employee added to the shared workforce roster.') }
  const addLeave = (event: FormEvent) => { event.preventDefault(); void save(async () => { await api('/leave', 'POST', { ...leave, employeeId: Number(leave.employeeId) }); setLeave({ employeeId: '', startsOn: '', endsOn: '', leaveType: 'Annual leave', sourceReference: '' }) }, 'Approved leave added to the shared work calendar.') }
  const addHoliday = (event: FormEvent) => { event.preventDefault(); void save(async () => { await api('/holidays', 'POST', holiday); setHoliday({ holidayDate: '', name: '', region: 'default' }) }, 'Holiday added to the shared calendar.') }
  const title = tab === 'workforce' ? 'Workforce' : tab === 'leave' ? 'Leave records' : 'Holiday calendar'
  return <main className="employee-app hr-app"><aside className="employee-sidebar"><div className="employee-logo"><span>P</span> pulse<span>AI</span></div><p>HR WORKSPACE</p><nav>{([['workforce', 'Workforce', Users], ['leave', 'Leave', CalendarDays], ['calendar', 'Holidays', UserCog]] as const).map(([id, label, Icon]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon size={17} />{label}</button>)}</nav><div className="employee-user"><span>{user.name[0]}</span><div><strong>{user.name}</strong><small>Human Resources</small></div><button onClick={onSignOut} aria-label="Sign out"><LogOut size={16} /></button></div></aside>
    <section className="employee-content"><header className="employee-header"><div><h1>{title}</h1><p>Shared workforce data for Employee, Manager, and Director workflows</p></div></header>
      {message && <div className="employee-message" role="status">{message}<button onClick={() => setMessage('')} aria-label="Dismiss message">×</button></div>}{error && <div className="employee-message hr-error" role="alert">{error}<button onClick={() => { setError(''); void load() }}>Try again</button></div>}
      {!data ? <p className="employee-loading">Loading workforce records…</p> : <><dl className="hr-metrics"><div><dt>Workforce records</dt><dd>{data.summary.employees || 0}</dd></div><div><dt>Active</dt><dd>{data.summary.activeEmployees || 0}</dd></div><div><dt>Inactive</dt><dd>{data.summary.inactiveEmployees || 0}</dd></div></dl>
        {tab === 'workforce' && <><section className="hr-section"><div className="employee-section-heading"><div><h2>Add workforce record</h2><span>New employees enter the same roster used by Manager assignments and Director reporting.</span></div></div><form className="hr-form" onSubmit={addEmployee}><label>Workforce ID<input value={employee.employeeCode} onChange={e => setEmployee({ ...employee, employeeCode: e.target.value })} required maxLength={30} placeholder="E501" /></label><label>Employee name<input value={employee.name} onChange={e => setEmployee({ ...employee, name: e.target.value })} required maxLength={120} /></label><label>Work email<input type="email" value={employee.email} onChange={e => setEmployee({ ...employee, email: e.target.value })} required /></label><label>Department<select value={employee.departmentId} onChange={e => setEmployee({ ...employee, departmentId: e.target.value })} required><option value="">Choose department</option>{data.departments.map((row: any) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Reporting Manager<select value={employee.managerUserId} onChange={e => setEmployee({ ...employee, managerUserId: e.target.value })} required><option value="">Choose Manager</option>{data.managers.map((row: any) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button className="employee-primary" disabled={saving || !data.departments.length || !data.managers.length}>{saving ? 'Saving…' : 'Add employee'}</button></form>{!data.managers.length && <p className="hr-note">Configure at least one Manager account before assigning employees.</p>}</section>
          <section className="hr-section hr-table"><div className="employee-section-heading"><div><h2>Employee roster</h2><span>Changes apply to future team access; historical records remain linked.</span></div><span>{data.employees.length} records</span></div><div className="employee-table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Reporting Manager</th><th>Access</th><th>Pending reviews</th><th>Action</th></tr></thead><tbody>{data.employees.map((row: any) => <RosterRow key={row.id} row={row} data={data} saving={saving} onSave={(values: any) => save(() => api(`/employees/${row.id}`, 'PATCH', values), 'Workforce record updated. Historical approvals are unchanged.')} />)}</tbody></table>{!data.employees.length && <p className="hr-empty">No employee records yet.</p>}</div></section></>}
        {tab === 'leave' && <><section className="hr-section"><div className="employee-section-heading"><div><h2>Record approved leave</h2><span>Leave is excluded from Employee missing-workday checks and Manager/Director exceptions.</span></div></div><form className="hr-form" onSubmit={addLeave}><label>Employee<select value={leave.employeeId} onChange={e => setLeave({ ...leave, employeeId: e.target.value })} required><option value="">Choose employee</option>{data.employees.map((row: any) => <option key={row.id} value={row.id}>{row.name} · {row.employeeCode}</option>)}</select></label><label>Leave type<input value={leave.leaveType} onChange={e => setLeave({ ...leave, leaveType: e.target.value })} required maxLength={80} /></label><label>Start date<input type="date" value={leave.startsOn} onChange={e => setLeave({ ...leave, startsOn: e.target.value })} required /></label><label>End date<input type="date" value={leave.endsOn} min={leave.startsOn || undefined} onChange={e => setLeave({ ...leave, endsOn: e.target.value })} required /></label><label>Reference (optional)<input value={leave.sourceReference} onChange={e => setLeave({ ...leave, sourceReference: e.target.value })} maxLength={120} /></label><button className="employee-primary" disabled={saving}>{saving ? 'Saving…' : 'Record approved leave'}</button></form></section><section className="hr-section hr-table"><div className="employee-section-heading"><div><h2>Leave history</h2></div></div><div className="employee-table-wrap"><table><thead><tr><th>Employee</th><th>Leave type</th><th>Dates</th><th>Reference</th><th>Status</th><th /></tr></thead><tbody>{data.leaves.map((row: any) => <tr key={row.id}><td>{row.employeeName}<small>{row.employeeCode}</small></td><td>{row.leaveType}</td><td>{row.startsOn} – {row.endsOn}</td><td>{row.sourceReference || '—'}</td><td>{row.status}</td><td><button className="hr-text-action" disabled={saving} onClick={() => void save(() => api(`/leave/${row.id}`, 'PATCH', { status: row.status === 'approved' ? 'cancelled' : 'approved' }), row.status === 'approved' ? 'Leave cancelled.' : 'Leave restored.')}>{row.status === 'approved' ? 'Cancel' : 'Restore'}</button></td></tr>)}</tbody></table>{!data.leaves.length && <p className="hr-empty">No leave records are available.</p>}</div></section></>}
        {tab === 'calendar' && <><section className="hr-section"><div className="employee-section-heading"><div><h2>Add public holiday</h2><span>Active holidays are excluded from missing-workday calculations across roles.</span></div></div><form className="hr-form hr-holiday-form" onSubmit={addHoliday}><label>Date<input type="date" value={holiday.holidayDate} onChange={e => setHoliday({ ...holiday, holidayDate: e.target.value })} required /></label><label>Holiday name<input value={holiday.name} onChange={e => setHoliday({ ...holiday, name: e.target.value })} required maxLength={120} /></label><label>Region<input value={holiday.region} onChange={e => setHoliday({ ...holiday, region: e.target.value })} required maxLength={60} /></label><button className="employee-primary" disabled={saving}>{saving ? 'Saving…' : 'Add holiday'}</button></form></section><section className="hr-section hr-table"><div className="employee-section-heading"><div><h2>Holiday calendar</h2></div></div><div className="employee-table-wrap"><table><thead><tr><th>Date</th><th>Holiday</th><th>Region</th><th>Status</th><th /></tr></thead><tbody>{data.holidays.map((row: any) => <tr key={row.id}><td>{row.holidayDate}</td><td>{row.name}</td><td>{row.region}</td><td>{row.active ? 'Active' : 'Inactive'}</td><td><button className="hr-text-action" disabled={saving} onClick={() => void save(() => api(`/holidays/${row.id}`, 'PATCH', { active: !row.active }), row.active ? 'Holiday deactivated.' : 'Holiday restored.')}>{row.active ? 'Deactivate' : 'Restore'}</button></td></tr>)}</tbody></table>{!data.holidays.length && <p className="hr-empty">No public holidays are configured.</p>}</div></section></>}
      </>}</section></main>
}

function RosterRow({ row, data, saving, onSave }: { row: any; data: any; saving: boolean; onSave: (values: any) => void }) {
  const [departmentId, setDepartmentId] = useState(String(row.departmentId)); const [managerUserId, setManagerUserId] = useState(String(row.managerUserId || '')); const [active, setActive] = useState(Boolean(row.active)); const [reassign, setReassign] = useState(false)
  const changed = departmentId !== String(row.departmentId) || managerUserId !== String(row.managerUserId || '') || active !== Boolean(row.active)
  return <tr><td><strong>{row.name}</strong><small>{row.employeeCode} · {row.email}</small></td><td><select aria-label={`Department for ${row.name}`} value={departmentId} onChange={e => setDepartmentId(e.target.value)}>{data.departments.map((option: any) => <option value={option.id} key={option.id}>{option.name}</option>)}</select></td><td><select aria-label={`Manager for ${row.name}`} value={managerUserId} onChange={e => setManagerUserId(e.target.value)}>{data.managers.map((option: any) => <option value={option.id} key={option.id}>{option.name}</option>)}</select>{Number(row.pendingReassignmentCount) > 0 && <label className="hr-reassign"><input type="checkbox" checked={reassign} onChange={e => setReassign(e.target.checked)} /> Reassign {row.pendingReassignmentCount} pending review{row.pendingReassignmentCount === 1 ? '' : 's'} to this Manager</label>}</td><td><label className="hr-active"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> {active ? 'Active' : 'Inactive'}</label></td><td>{row.upcomingLeaveCount ? `${row.upcomingLeaveCount} upcoming` : '—'}</td><td><button className="hr-text-action" disabled={saving || (!changed && !reassign) || !managerUserId} onClick={() => onSave({ departmentId: Number(departmentId), managerUserId: Number(managerUserId), active, reassignPendingReviews: reassign })}>Save</button></td></tr>
}
